version: 0.2

env:
  variables:
    key: "nonsecuretest"
#  parameter-store:
#    securekeytest: "securetest"

phases:
  install:
    commands:
      - echo "install running..."
#      - apt-get install -y python python-pip
#      - pip install aws
      - echo "install worked!!!"
  pre_build:
    commands:
      - echo "pre_build running..."
      - echo "pre_build worked!!!"
  build:
    commands:
      - echo "build running..."
      - echo "build worked!!!"
  post_build:
    commands:
      - echo "post_build running..."
      - timestamp=$(date +%s)
      - zip artifact-${timestamp}.zip index.html
      - aws s3 cp artifact-${timestamp}.zip s3://${DEPLOY_BUCKET}/${DEPLOY_BUCKET_KEY}/artifact-${timestamp}.zip
      - aws s3 cp artifact-${timestamp}.zip s3://${DEPLOY_BUCKET}/${DEPLOY_BUCKET_KEY}/artifact-latest.zip
      - echo "post_build worked!!!"
artifacts:
  files:
    - index.html
  discard-paths: yes
